name: Abubakar's github actions testing
run-name: linter
on: 
  push: 
    branches: 
      - main

jobs: 
  my_first_job: # <-- job_id
    name: My first job # <-- displayed in the GitHub UI
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository # <-- displayed in the GitHub UI
        uses: actions/checkout@v3
      
      - name: My second step # <-- displayed in the GitHub UI
        run: echo "Hello, world"
        
        
      

      

