on: 
  push: 
    branches: 
      - main

jobs: 
  my_first_job: # <-- job_id
    name: My first job # <-- displayed in the GitHub UI
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository # <-- displayed in the GitHub UI
        uses: actions/checkout@v3
      
      - name: Set up Terraform # <-- displayed in the GitHub UI
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials # <-- displayed in the GitHub UI
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init # <-- displayed in the GitHub UI
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve

        
        
      

      

