name: Abubakar's workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

jobs: 
  my_job_id: 
    name: Terraform Job
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: terraform fmt
      - run: terraform validate
      - run: terraform plan


    