name: Abubakar's workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

jobs: 
  some_job_id: # <-- Some job_id
    name: This is a job # <-- Name of the job which is displayed in the GitHub UI
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - run: echo "Hello World!"

    