name: Abubakar's workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

jobs: 
  some_job_id: # <-- Some job_id
    name: Some job # <-- Name of the job which is displayed in the GitHub UI
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
        name: Checkout Repository # <-- Name of the step which is displayed in the GitHub UI
      - run: echo "Hello World!"
    
  some_other_job_id: # <-- Some other job_id
    needs: some_job_id
    name: Some other job # <-- Name of the other job which is displayed in the GitHub UI
    runs-on: ubuntu-latest

    steps: 
      - run: echo "Goodbye World!"
  
  another_job_id: 
    needs: some_other_job_id
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello World"


    